# Generated by Django 5.2.8 on 2026-01-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='primary_whatsapp_mobile_number',
            new_name='is_primary_whatsapp',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='secondary_whatsapp_mobile_number',
            new_name='is_secondary_whatsapp',
        ),
    ]
