# Generated by Django 5.2.8 on 2026-01-13 09:56

import auth_system.utils.driver_document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_insert_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_document',
            name='driver',
        ),
        migrations.AlterField(
            model_name='driver_document',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to=auth_system.utils.driver_document.driver_document_path),
        ),
        migrations.AlterField(
            model_name='driver_document',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to=auth_system.utils.driver_document.driver_document_path),
        ),
        migrations.AlterField(
            model_name='driver_document',
            name='insurance_copy',
            field=models.FileField(blank=True, null=True, upload_to=auth_system.utils.driver_document.driver_document_path),
        ),
        migrations.AlterField(
            model_name='driver_document',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to=auth_system.utils.driver_document.driver_document_path),
        ),
        migrations.AlterField(
            model_name='driver_document',
            name='selfie',
            field=models.FileField(blank=True, null=True, upload_to=auth_system.utils.driver_document.driver_document_path),
        ),
    ]
