# Generated by Django 6.0.3 on 2026-03-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_user_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_logout_history',
            name='concurrent_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login_logout_history',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login_logout_history',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
