# Generated by Django 5.2.8 on 2026-01-13 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_remove_driver_document_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_document',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
