# Generated by Django 5.2.8 on 2026-02-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_alter_user_latitude_alter_user_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_security',
            name='faceLock',
        ),
        migrations.RemoveField(
            model_name='user_security',
            name='fingerprint',
        ),
        migrations.RemoveField(
            model_name='user_security',
            name='is_face_lock_enabled',
        ),
        migrations.RemoveField(
            model_name='user_security',
            name='is_fingerprint_enabled',
        ),
    ]
