# Generated by Django 5.2.8 on 2026-01-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_driver_document_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_whatsapp_mobile_number',
            field=models.CharField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_mobile_number',
            field=models.BooleanField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_whatsapp_mobile_number',
            field=models.BooleanField(default=False),
        ),
    ]
