# Generated by Django 6.0.3 on 2026-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_login_logout_history_concurrent_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_logout_history',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
