# Generated by Django 6.0.3 on 2026-03-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_login_logout_history_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_logout_history',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
