# Generated by Django 5.2.8 on 2026-01-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_alter_user_secondary_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_whatsapp_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_whatsapp_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
