# Generated by Django 6.0.2 on 2026-04-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0009_alter_user_email_id_alter_user_primary_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermpinhistory',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
