# Generated by Django 6.0.2 on 2026-04-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0010_usermpinhistory_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_attempts',
        ),
        migrations.RemoveField(
            model_name='usermpinhistory',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='password_history',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
