# Generated by Django 6.0.2 on 2026-04-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0011_remove_user_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermpinhistory',
            name='mpin_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
