# Generated by Django 6.0.2 on 2026-04-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0012_usermpinhistory_mpin_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='password_history',
            name='is_password_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
